### ISSUE TITLE
[Feat] PR 자동 merge 및 remote branch 삭제 기능

### ISSUE THREAD

**Issue by youngmin-gwon** [PLAIF-dev/core_template#11]
### 설명

1. 필요조건이 되면(ex. 특정한 사람이 승인, 2명이 승인) github action이 자동으로 돌면서 branch를 merge 합니다.
2. merge가 문제 없이 되면 remote branch를 삭제합니다.

### 제약 사항

1. 기존 기능에 영향을 끼치면 안됩니다.

### 추가 내용

@pjs102793 님, 이 기능이 필요한지 의견을 나누기 위해 issue를 열었습니다. 자유롭게 의견을 나눠주시고 필요하다고 서로 동의하면 기능을 추가하도록 하겠습니다.

**Comment by pjs102793** [comment]
있으면 확실히 좋은 기능인 것 같습니다. 아까 말씀 드렸던 승인이 되고나서 commit하는 부분을 PR을 Re-Open하기만 하면 딱히 단점은 없을 것 같습니다.

그리고, merge하는 부분을 통일 할 수 있어서도 좋은 것 같구요, squash로 할지 안 할지만 정하면 될 것 같습니다.

**Comment by powerstrong** [comment]
@youngmin-gwon squash할 때의 커밋 메시지도 자동으로 작성되는 건가요?
그리고 병합 시점을 사실상 리뷰어가 결정하게 되는데, 작업자가 코드를 다듬을 여지가 없어지는게 좀 걱정이 되네요~

**Comment by youngmin-gwon** [comment]
@powerstrong 그 점은 @pjs102793 님 또한 걱정해주셨던 부분이었습니다. 그 때 제가 낸 의견은

`추후에 더 다듬어야 하면 작업자가 issue를 reopen 해서 다시 pr을 받게 하기`

였습니다. 승인된 부분에서 문제가 없었다가, 다시 다듬다가 문제가 생겨질 수 있는 부분도 방지할 수 있는 것 역시 덤이라고 생각했거든요.
해당안에 대해서 피드백 부탁드립니다.

**Comment by powerstrong** [comment]
@youngmin-gwon 
추후에 더 다듬어야 하면 작업자가 issue를 reopen 해서 다시 pr을 받게 하기
-> 좋습니다!

Squash할 때 커밋메시지가 뭘로 들어갈 것인가? 마지막 커밋메시지? 이슈이름?
-> 좋은 방법이 있는지 확인 한 번 해주시면 감사하겠습니다

**Comment by youngmin-gwon** [comment]
action을 만들지 않고 설정하는 방법을 찾았습니다. 설정하는 방법 및 사용법은 다음 [discussion](https://github.com/orgs/PLAIF-dev/discussions/7#discussioncomment-6117706) 을 참고해주세요!

@powerstrong 확인 하신 이후 제가 issue 닫겠습니다.

**Comment by youngmin-gwon** [comment]
확인 하셔서 해당 이슈를 종료합니다.
