### ISSUE TITLE
[Docs] 리파지토리 네이밍 규칙

### ISSUE THREAD

**Issue by pjs102793** [PLAIF-dev/core_template#12]
### 설명

리파지토리가 슬슬 많아지고 있으며, 전체적으로 난잡한 느낌이 나고 있습니다. 예를 들어서, DLManager-Model-Zoo와 같은 이름이 있고, piecepicking_vision 이렇게 규칙없이 리파지토리 이름이 작성이 되고 있는 것 같습니다.

그래서 리파지토리의 이름 규칙이 있으면 좋을 것 같습니다. 이전에 @youngmin-gwon 님과 함께 대화를 했었는데,
대화의 결론은 snake_case가 전에 사용하기 좋다고 결론이 났었고, vision_~~~, motion_~~~, sw_~~~ 로 리파지토리에 팀이름을 붙이는 것도 추가하기로 했습니다.

예를 들어서 DLManager-Model-Zoo이런 이름을 vision_dlmanager_model_zoo 이렇게 수정하면 됩니다.
piecepicking_vison도 vision_piecepicking으로 바꿔야 할 것 같습니다.

위와 같은 내용은 Notion과 Core template에 추가할 예정입니다.

@youngmin-gwon 의견 공유 부탁드립니다.

**Comment by youngmin-gwon** [comment]
이전에 이야기 했던 내용이어서 이의 사항 없습니다. @powerstrong , @leewoojae , @gayounghan 님 모두 동의하시면 수정 진행하겠습니다.

**Comment by powerstrong** [comment]
좋은 의견입니다!
한편으로 다수의 팀원이 공동작업하는 저장소가 있으면 어떡하지라는 걱정이 있긴 한데...
그래도 지금보다 나을 것 같아서 찬성입니다!

**Comment by pjs102793** [comment]
> 좋은 의견입니다! 한편으로 다수의 팀원이 공동작업하는 저장소가 있으면 어떡하지라는 걱정이 있긴 한데... 그래도 지금보다 나을 것 같아서 찬성입니다!

이 부분은 따로 CamelCase로 구성하고, 프로젝트 명칭을 두는게 어떨까요? 팀별로 개개인으로 작업하는 리파지토리는 모두 snake_case면 CamelCase로 된 리파지토리 이름은 자연스럽게 일종의 프로젝트구나 라고 생각이 들 거 같아서요.

**Comment by youngmin-gwon** [comment]
@powerstrong 그런 작업은 col(collaborative)이나 다른 명칭으로 정하는 것이 어떨까요? 더 잘 설명하는 의미이면 저는 뭐든 좋을거 같습니다.

**Comment by powerstrong** [comment]
그때그때 바꾸면 되는거라 생각하니 마음이 놓이네요. 감사합니다. ㅎㅎ

**Comment by leewoojae** [comment]
회신이 늦어 죄송합니다.
저도 동의합니다. Motion 팀 리파지토리 만들때 적용하겠습니다.

**Comment by gayounghan** [comment]
저도 회신이 늦어 죄송합니다.
동의하는 바이나 추가 의견이 있어 말씀 드립니다.
팀 구분 시 앞에 붙이는 것은 간략하게
vision -> vs
motion -> mo
이 어떨까요?

**Comment by youngmin-gwon** [comment]
> 저도 회신이 늦어 죄송합니다.
> 동의하는 바이나 추가 의견이 있어 말씀 드립니다.
> 팀 구분 시 앞에 붙이는 것은 간략하게
> vision -> vs
> motion -> mo
> 이 어떨까요?

@gayounghan 좋은 의견 감사합니다. 간결해서 쉽게 보고 찾을 수 있을거 같습니다. 공통으로 작성할만한 약속 규칙 같은 것을 같이 볼 수 있는 깃허브 readme나 notion 페이지에 따로 정리하면 추후에 인수인계하기도 쉬울거 같다는 생각이 듭니다.

추가적으로 @leewoojae, @gayounghan, @powerstrong 팀장님들에게 부탁드리고 싶은 것은,
>1. 팀원들에게 repository 이름 규칙 알려주기
>2. 기존에 생성되어 있는 repository에 대해 git remote 변경해주기
입니다.

@pjs102793

**Comment by pjs102793** [comment]
그러면 vs_~~~ mo_~~~ sw_~~~ 로 정리 하는 걸로 하고 문서 작성 및 docs 추가하겠습니다.
여러 팀에서 작업하는 것은 추후 그러한 리파지토리가 추가되면 다시 이슈를 여는 것으로 하시죠

@youngmin-gwon
