### ISSUE TITLE
[CI] template sync를 하는 github action 추가하기

### ISSUE THREAD

**Issue by youngmin-gwon** [PLAIF-dev/core_template#13]
### 설명

1. 템플릿을 이용해서 레포를 생성한 이후에 생기는 템플릿 변경은 미리 생성된 레포에 반영되지 않습니다. 이런 변경사항을 파생 레포에 반영할 수 있는 github action을 추가합니다.

### 제약 사항

1. `.github` 폴더를 제외하고는 수정하지 않아야 합니다.

**Comment by youngmin-gwon** [comment]
@pjs102793 
혹시 해당 작업을 PR 하실 때, `./labels.json` 파일 삭제해서 보내주실수 있을까요? 이 문제와 연관이 있고 더 이상 필요하지 않은 파일 같습니다.

**Comment by pjs102793** [comment]
> @pjs102793 혹시 해당 작업을 PR 하실 때, `./labels.json` 파일 삭제해서 보내주실수 있을까요? 이 문제와 연관이 있고 더 이상 필요하지 않은 파일 같습니다.

알겠습니다. 반영해서 PR 보내겠습니다!

**Comment by pjs102793** [comment]
@youngmin-gwon 

개발하는데에 여러 문제점이 생겨서 PR하기 전에 확인받으려고 합니다.
문제점은 다음과 같습니다.

### 1. .github/workflows/* 파일들을 수정할 수 없습니다.
이는 해당 앱에서도 어쩔 수 없는 부분이라고 합니다. 그 이유는 github 측에서 workflows를 수정하는 권한은 주어지지 않는다고 합니다. 그래서 workflows 폴더 내부는 동기화 할 수 없다고 합니다. 마찬가지로 다른 앱이나 무슨 수를 쓰든 actions 내부에서 workflows를 수정할 수 없을 것 같습니다. 이에 대한 해결책은 .gitignore 처럼 sync 할 때 예외를 줄 수 있는데 .github/workflows/*를 추가해줘야 한다고 합니다. 실제로 이 앱을 만든 개발자도 .github/workflows/*를 추가해서 사용하고 있었습니다.
### 2. template 리파지토리에 파일이 삭제되도 이는 반영되지 않습니다.
template에는 md 파일이 삭제되었지만, sync를 작동 시켰을때 지워지지 않았습니다. 사실 이는 당연한 작동인데 만약에 지워지게 되는 거라면 리파지토리에 .github 폴더에 파일을 추가하면 사라진다는 의미입니다.
### 3. template에 있는 파일을 수정할 수 없다.
이게 제일 치명적인 문제인데, template에 있는 파일은 임의의 프로젝트에서 수정할 수 없습니다.
<img width="1230" alt="스크린샷 2023-06-08 오후 9 43 22" src="https://github.com/PLAIF-dev/core_template/assets/53421022/af462103-0408-464d-a509-abe798f352bb">
위 사진을 보시면 이 앱의 PR 내용입니다. 앱에서 보낸 거의 모든 PR을 Close 시킨 것을 볼 수 있습니다. 그 이유는 템플릿에서 없는 내용이 리파지토리에 추가 되면 리파지토리의 내용이 지워지고 있었고, 리파지토리에서 지운 내용이 템플릿에 있는 내용으로 PR을 보내고 있었습니다.
이는 템플릿에 완전하게 고정이 되는 것이며 개발의 유연성을 해치는 것이라고 생각됩니다. 게다가 자신이 만든 앱인데, 그 앱에서 보낸 PR을 모두 거절하고 있는 모습을 보면 그리 개발에 좋은 상황은 아니라고 생각됩니다.

의견 공유 부탁드립니다.

**Comment by youngmin-gwon** [comment]
@pjs102793 
상황 업데이트 감사드립니다.

지금 생각난 프로세스는 우회로 같은 방법입니다.  다음 같은 프로세스는 어떤지 의견 부탁드립니다.

1. 현재 레포를 template -> 기본 레포로 변환
2. 추후 레포를 새로 만들 때는 `fork` 로 만들기
3. template 레포에서 변경이 있을 때는 fork `sync`로 반영

이러한 프로세스로 전환한다면 문제는 더 간단하게 auto fork syncer 같은 것만 있어 cron 형태로 돌려주기만 하면 될거 같습니다.

늦은시간까지 노고에 감사드립니다.

**Comment by pjs102793** [comment]
git template를 remote에 추가하고 cherry-pick으로 가져오는 것으로 대체 하려고 하기 때문에 이 Issue를 닫겠습니다.
