### ISSUE TITLE
[Feat] Auto Labels 구성

### ISSUE THREAD

**Issue by pjs102793** [PLAIF-dev/core_template#8]
### 설명

1. Issue에 따로 label을 추가하지 않아도 자동으로 label을 추가해주는 기능을 추가합니다.
2. Github에 제공되는 Label 관련 앱 2개를 테스트해보고 도입을 합니다.

### 제약 사항

1. 각 Issue template에 맞는 Labels를 자동적으로 달아준다.

**Comment by youngmin-gwon** [comment]
@pjs102793 Github Apps 두 가지 모두 제대로 사용하기 어려워, github actions로 전환합니다 😿

**Comment by powerstrong** [comment]
@pjs102793  @youngmin-gwon 알아서 척척 좋은 기능들 많이 만들어주셔서 감사합니다! 

영민
님짱

**Comment by youngmin-gwon** [comment]
기능을 대체할 수 있을거 같아서 이슈를 마감합니다.
